version: 2.1
jobs:
  convert:
    working_directory: ~/circlecitest
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: |
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: content
          paths: .
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          command: |
            hugo
      - persist_to_workspace:
          root: public
          paths: .

  deploy:
    machine:
      enable: true
    steps:
      - add_ssh_keys:
          fingerprints:
           - "SHA256:VzyVZmdNbkU2EFHSP0OQSHK5AfeZ5d7aVnYmCrwVlsI winhtet1997@gmail.com"
      - checkout
      - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "python -m http.server 8000"

workflows:
  version: 2.1
  build:
    jobs:
      - convert
      - build:
          requires:
            - convert
      - deploy:
          requires:
            - build
