version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - convert
      - build:
          requires:
            - convert
      - deploy:
          requires:
            - build

jobs:
  convert:
    working_directory: ~/circlecitest
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: |
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: .
          paths:
            - content
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          command: |
            hugo
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
           - "SHA256:6VpFJAKjenFTnN+RbUIATGyhWnKJ3BRK14lDBQFhTtQ winhtet1997@gmail.com"
      - checkout
      - run:
           name: Deploy
           command: |
             git clone --single-branch --branch master git@github.com:winhtet-mlc/circlecitest.git master
             cd master
             git config user.name "winhtet-mlc"
             git config user.email "winhtet1997@gmail.com"
             git add .
             git commit -m "Automated deployment job"
             git push origin master
