version: 2.1
jobs:
  convert:
    docker:
      - image: jupyter/datascience-notebook
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: |
            docker run -it --rm -p 8888:8888 -p 4040:4040 -v ~/circlecitest:/home/jovyan/workspace jupyter/datascience-notebook
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
          working_directory: ~/circlecitest
      - persist_to_workspace:
          root: content
          paths: .
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/content
    environment:
      HUGO_BUILD_DIR: public
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Rv/k4RqvmRlcCpuuilLxk9TePZ+unXvAOvUZwgF/u3Q winhtet1997@gmail.com"
      - checkout
      - run:
          command: |
            apk update && apk add git
            HUGO_ENV=production hugo -F -v -d $HUGO_BUILD_DIR

  test:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Rv/k4RqvmRlcCpuuilLxk9TePZ+unXvAOvUZwgF/u3Q winhtet1997@gmail.com"
      - checkout
      - run:
          name: test the generated html files
          command: htmlproofer /src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external

workflows:
  build_and_test:
    jobs:
      - convert
      - build
      - test
