version: 2.1
jobs:
  build:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Rv/k4RqvmRlcCpuuilLxk9TePZ+unXvAOvUZwgF/u3Q winhtet1997@gmail.com"
      - checkout
      - run: git submodule update --init
      - run: hugo -v -s /src -d /src/public

  test:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Rv/k4RqvmRlcCpuuilLxk9TePZ+unXvAOvUZwgF/u3Q winhtet1997@gmail.com"
      - checkout
      - run:
          name: test the generated html files
          command: htmlproofer /src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external

  deploy:
    docker:
      - image: z0li/hugo-builder:latest
    working_directory: /src
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Rv/k4RqvmRlcCpuuilLxk9TePZ+unXvAOvUZwgF/u3Q winhtet1997@gmail.com"
      - checkout
      - run: git config user.name "CircleCI"
      - run: git config user.email ${GIT_EMAIL}
      - run: git add -A
      - run: git commit -m "Automated deployment job ${CIRCLE_BRANCH}"
      - run: git push origin master

workflows:
  build_and_test:
    jobs:
      - build
      - test
      - deploy
